-- Baseline schema for PostgreSQL.
--
-- The end state of the SQLite era — the original `schema.sql`, the ad-hoc
-- `ALTER TABLE` patches that used to run on every start, and migrations
-- 0001–0003 — written once in PostgreSQL's dialect. Data from an existing
-- SQLite deployment is copied in by `scripts/migrate_sqlite_to_postgres.py`.
--
-- Conventions kept on purpose so the application did not have to change:
-- flags stay INTEGER 0/1, JSON stays TEXT (cast to jsonb where a query needs
-- it), and every timestamp is TIMESTAMPTZ, which `app.db.database` hands back
-- as UTC `YYYY-MM-DD HH:MM:SS` exactly like SQLite's `datetime('now')`.

-- ═══ Papers, parses and analysis runs ═══════════════════════════════════════

CREATE TABLE papers (
    paper_id   TEXT PRIMARY KEY,                -- sha1(pdf_bytes)
    file_path  TEXT NOT NULL,                   -- relative to data_dir
    title      TEXT DEFAULT '',
    doi        TEXT DEFAULT '',
    venue      TEXT DEFAULT '',        -- journal/conference name from Crossref
    year       INTEGER DEFAULT 0,      -- publication year
    sci_rank   TEXT DEFAULT '',        -- SCI tier: Q1/Q2/Q3/Q4
    ccf_rank   TEXT DEFAULT '',        -- CCF rating: A/B/C
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE mineru_parses (
    parse_id          TEXT PRIMARY KEY,
    paper_id          TEXT NOT NULL REFERENCES papers(paper_id),
    backend           TEXT NOT NULL DEFAULT 'vlm',      -- vlm | pipeline
    status            TEXT NOT NULL DEFAULT 'pending',  -- pending | running | done | failed
    output_dir        TEXT DEFAULT '',
    error_msg         TEXT DEFAULT '',
    -- Remote poll diagnostics, so a stuck parse can be told from a slow one.
    remote_batch_id   TEXT DEFAULT '',
    poll_count        INTEGER DEFAULT 0,
    last_state_counts TEXT DEFAULT '',
    last_poll_at      TIMESTAMPTZ DEFAULT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_mineru_parses_paper ON mineru_parses(paper_id);

CREATE TABLE blocks (
    block_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id     TEXT NOT NULL REFERENCES papers(paper_id),
    type         TEXT NOT NULL DEFAULT '',      -- text | title | table | image | equation | code | list | ref_text ...
    sub_type     TEXT DEFAULT '',
    page_idx     INTEGER DEFAULT 0,
    bbox_json    TEXT DEFAULT '[]',    -- [x0, y0, x1, y1]
    text         TEXT DEFAULT '',
    section_path TEXT DEFAULT '',      -- e.g. "2.Method/2.1 Model"
    order_idx    INTEGER DEFAULT 0
);
CREATE INDEX idx_blocks_paper ON blocks(paper_id);
CREATE INDEX idx_blocks_type  ON blocks(paper_id, type);

-- Section hierarchy and retrieval chunks. `search_tsv` replaces the FTS5
-- virtual table SQLite needed: generated from the same two columns, so it can
-- never drift from the rows it indexes. 'simple' means no stemming and no
-- stopwords, matching what FTS5's unicode61 tokenizer did.
CREATE TABLE paper_nodes (
    node_id         TEXT PRIMARY KEY,
    paper_id        TEXT NOT NULL REFERENCES papers(paper_id),
    parent_id       TEXT DEFAULT '',
    depth           INTEGER DEFAULT 0,
    node_type       TEXT NOT NULL DEFAULT '',    -- paper | section | chunk
    block_type      TEXT DEFAULT '',    -- original block type for chunk nodes
    sub_type        TEXT DEFAULT '',
    title           TEXT DEFAULT '',
    title_path      TEXT DEFAULT '',
    page_start      INTEGER DEFAULT 0,
    page_end        INTEGER DEFAULT 0,
    block_start     INTEGER DEFAULT 0,
    block_end       INTEGER DEFAULT 0,
    text            TEXT DEFAULT '',
    text_for_search TEXT DEFAULT '',
    order_idx       INTEGER DEFAULT 0,
    search_tsv      TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('simple'::regconfig, coalesce(title_path, '') || ' ' || coalesce(text_for_search, ''))
    ) STORED
);
CREATE INDEX idx_paper_nodes_paper ON paper_nodes(paper_id);
CREATE INDEX idx_paper_nodes_parent ON paper_nodes(paper_id, parent_id);
CREATE INDEX idx_paper_nodes_type ON paper_nodes(paper_id, node_type);
CREATE INDEX idx_paper_nodes_search ON paper_nodes USING GIN (search_tsv);

CREATE TABLE runs (
    run_id           TEXT PRIMARY KEY,
    paper_id         TEXT NOT NULL REFERENCES papers(paper_id),
    mode             TEXT NOT NULL DEFAULT 'snap',     -- snap | lens | sphere | auto | qa
    llm_model        TEXT DEFAULT '',
    language         TEXT NOT NULL DEFAULT 'en',       -- en | zh
    status           TEXT NOT NULL DEFAULT 'pending',  -- pending | running | done | failed
    error_msg        TEXT DEFAULT '',
    started_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at      TIMESTAMPTZ DEFAULT NULL,
    user_question    TEXT DEFAULT '',
    detected_intent  TEXT DEFAULT '',
    current_step     TEXT DEFAULT '',         -- last step pushed via progress (for resume UI)
    progress_json    TEXT DEFAULT '[]',       -- JSON array of {step,status,...} emitted so far
    owner_token      TEXT DEFAULT '',         -- per-browser owner token, scopes recent-runs listing
    -- Set when a mode report is produced inside an agent conversation (P5).
    agent_session_id TEXT DEFAULT '',
    agent_run_id     TEXT DEFAULT ''
);
CREATE INDEX idx_runs_status_started ON runs(status, started_at DESC);
CREATE INDEX idx_runs_started ON runs(started_at DESC);
CREATE INDEX idx_runs_paper ON runs(paper_id);
CREATE INDEX idx_runs_owner_started ON runs(owner_token, started_at DESC);
CREATE INDEX idx_runs_agent_session
    ON runs(agent_session_id, started_at DESC) WHERE agent_session_id <> '';

-- Anonymous traffic aggregates. visitor_hash is a SHA-256 digest of the
-- per-browser owner token; the raw token and network address are not stored.
CREATE TABLE traffic_visitors (
    visitor_hash  TEXT PRIMARY KEY,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    visit_count   INTEGER NOT NULL DEFAULT 1,
    last_path     TEXT NOT NULL DEFAULT ''
);
CREATE INDEX idx_traffic_visitors_last_seen ON traffic_visitors(last_seen_at DESC);

CREATE TABLE run_outputs (
    run_id    TEXT PRIMARY KEY REFERENCES runs(run_id),
    markdown  TEXT DEFAULT '',
    json_data TEXT DEFAULT '{}'
);

-- Cached external triage evidence per paper (Insight Snap). Keyed by paper,
-- not by run, so re-analysing the same PDF costs no extra API calls. Rows carry
-- a fetch timestamp because citation counts drift; see SNAP_SIGNALS_TTL_HOURS.
CREATE TABLE paper_signals (
    paper_id       TEXT PRIMARY KEY REFERENCES papers(paper_id),
    signals_json   TEXT NOT NULL DEFAULT '{}',   -- serialized TriageSignals
    cited_by_count INTEGER DEFAULT 0,   -- denormalized for list views
    is_retracted   INTEGER DEFAULT 0,   -- denormalized red flag
    fetched_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sphere_nodes (
    node_id         TEXT NOT NULL,
    run_id          TEXT NOT NULL REFERENCES runs(run_id),
    doi             TEXT DEFAULT '',
    arxiv_id        TEXT DEFAULT '',
    openalex_id     TEXT DEFAULT '',
    s2_paper_id     TEXT DEFAULT '',
    title           TEXT DEFAULT '',
    year            INTEGER DEFAULT 0,
    venue           TEXT DEFAULT '',
    authors         TEXT DEFAULT '',
    abstract_text   TEXT DEFAULT '',
    cited_by_count  INTEGER DEFAULT 0,
    pdf_path        TEXT DEFAULT '',
    mineru_parsed   INTEGER DEFAULT 0,
    source          TEXT DEFAULT 'seed_ref',
    score_total     DOUBLE PRECISION DEFAULT 0.0,
    layer           INTEGER DEFAULT 0,
    cluster_id      INTEGER DEFAULT -1,
    tier            INTEGER DEFAULT 3,              -- provenance trust tier (1 strongest)
    relation_type   TEXT DEFAULT 'unknown',         -- foundation|method_neighbor|competitor|follow_up|application|unrelated|unknown
    relevance       INTEGER DEFAULT -1,             -- LLM gate 0-3; -1 = not judged
    relation_reason TEXT DEFAULT '',
    quality_score   DOUBLE PRECISION DEFAULT 0.0,   -- citations/venue/recency composite
    sci_rank        TEXT DEFAULT '',                -- EasyScholar SCI quartile
    ccf_rank        TEXT DEFAULT '',                -- EasyScholar CCF tier
    influential     INTEGER DEFAULT 0,              -- S2 isInfluential citation flag
    PRIMARY KEY (node_id, run_id)
);
CREATE INDEX idx_sphere_nodes_run ON sphere_nodes(run_id);

CREATE TABLE sphere_edges (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         TEXT NOT NULL REFERENCES runs(run_id),
    source_node_id TEXT NOT NULL,
    target_node_id TEXT NOT NULL,
    edge_type      TEXT NOT NULL DEFAULT 'cites',
    weight         DOUBLE PRECISION DEFAULT 1.0
);
CREATE INDEX idx_sphere_edges_run ON sphere_edges(run_id);

-- ═══ Agent: identity, sessions, runs, events ════════════════════════════════
-- Deliberately parallel to the `runs` tables rather than folded into them:
-- `runs.paper_id` is NOT NULL, which cannot express a research task that
-- starts with no attachment or one that spans several papers.

-- Server-issued principals. The browser's `owner_token` is client generated
-- and therefore unforgeable only for listing; agent resources are scoped to a
-- principal whose credential the server signs and verifies.
CREATE TABLE agent_principals (
    principal_id TEXT PRIMARY KEY,
    kind         TEXT NOT NULL DEFAULT 'anonymous',  -- anonymous | user
    label        TEXT NOT NULL DEFAULT '',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE agent_sessions (
    session_id  TEXT PRIMARY KEY,
    owner_id    TEXT NOT NULL REFERENCES agent_principals(principal_id),
    -- LangGraph thread. Held as its own column so a session could be re-threaded
    -- (e.g. after a compaction) without changing its public id.
    thread_id   TEXT NOT NULL,
    title       TEXT NOT NULL DEFAULT '',
    language    TEXT NOT NULL DEFAULT 'zh',
    llm_model   TEXT NOT NULL DEFAULT '',
    config_json TEXT NOT NULL DEFAULT '{}',
    status      TEXT NOT NULL DEFAULT 'active',   -- active | archived
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_agent_sessions_owner ON agent_sessions(owner_id, updated_at DESC);
CREATE UNIQUE INDEX idx_agent_sessions_thread ON agent_sessions(thread_id);

CREATE TABLE agent_runs (
    run_id            TEXT PRIMARY KEY,
    session_id        TEXT NOT NULL REFERENCES agent_sessions(session_id),
    owner_id          TEXT NOT NULL,
    -- Client-supplied idempotency key: resubmitting the same key returns the
    -- original run instead of starting a second one (acceptance case A12).
    client_request_id TEXT NOT NULL DEFAULT '',
    status            TEXT NOT NULL DEFAULT 'pending',  -- pending|running|done|failed|cancelled|interrupted
    cancel_requested  INTEGER NOT NULL DEFAULT 0,
    error_code        TEXT NOT NULL DEFAULT '',
    error_msg         TEXT NOT NULL DEFAULT '',
    -- Budget ceilings for this run and what it actually consumed, both JSON so
    -- new dimensions do not need a migration.
    budget_json       TEXT NOT NULL DEFAULT '{}',
    usage_json        TEXT NOT NULL DEFAULT '{}',
    llm_model         TEXT NOT NULL DEFAULT '',
    prompt_version    TEXT NOT NULL DEFAULT '',
    started_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at       TIMESTAMPTZ DEFAULT NULL,
    -- Worker lease (P4). Without a record of *which* worker and when it was
    -- last alive, a run left `running` by a crash is indistinguishable from one
    -- that is merely slow. With a heartbeat, an orphan is a fact rather than an
    -- assumption (acceptance case A13).
    worker_id         TEXT NOT NULL DEFAULT '',
    heartbeat_at      TIMESTAMPTZ DEFAULT NULL
);
CREATE INDEX idx_agent_runs_session ON agent_runs(session_id, started_at DESC);
CREATE INDEX idx_agent_runs_owner_started ON agent_runs(owner_id, started_at DESC);
-- One in-flight run per session; a second concurrent submit must get a 409.
CREATE UNIQUE INDEX idx_agent_runs_active
    ON agent_runs(session_id) WHERE status IN ('pending', 'running');
-- Idempotency is per session, and only for callers that supplied a key.
CREATE UNIQUE INDEX idx_agent_runs_idempotent
    ON agent_runs(session_id, client_request_id) WHERE client_request_id <> '';
-- The orphan scan reads exactly this: active runs ordered by how stale they are.
CREATE INDEX idx_agent_runs_heartbeat
    ON agent_runs(status, heartbeat_at) WHERE status IN ('pending', 'running');

-- `seq` is allocated per session under an advisory lock (see
-- `agent_repository`); the unique index is what turns a mistake there into an
-- error instead of two messages silently sharing a position.
CREATE TABLE agent_messages (
    message_id     TEXT PRIMARY KEY,
    session_id     TEXT NOT NULL REFERENCES agent_sessions(session_id),
    run_id         TEXT NOT NULL DEFAULT '',
    role           TEXT NOT NULL,                  -- user | assistant | system
    content        TEXT NOT NULL DEFAULT '',
    citations_json TEXT NOT NULL DEFAULT '[]',     -- evidence_id list backing the text
    seq            INTEGER NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_agent_messages_session ON agent_messages(session_id, seq);

-- Durable event log. Events are persisted before publishing so a reconnecting
-- client can replay from `seq` (`Last-Event-ID`) and de-duplicate.
CREATE TABLE agent_events (
    session_id     TEXT NOT NULL,
    seq            INTEGER NOT NULL,
    run_id         TEXT NOT NULL DEFAULT '',
    schema_version INTEGER NOT NULL DEFAULT 1,
    type           TEXT NOT NULL,
    payload_json   TEXT NOT NULL DEFAULT '{}',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (session_id, seq)
);
CREATE INDEX idx_agent_events_run ON agent_events(run_id, seq);

-- ═══ Literature identity and versioned parses ═══════════════════════════════

-- A candidate paper, which may never acquire a local PDF. Kept distinct from
-- `papers` (whose id is sha1 of the file) because one work can have several
-- files and a file can exist with no external identifier.
CREATE TABLE literature_items (
    literature_id     TEXT PRIMARY KEY,
    doi               TEXT NOT NULL DEFAULT '',
    arxiv_id          TEXT NOT NULL DEFAULT '',
    openalex_id       TEXT NOT NULL DEFAULT '',
    s2_paper_id       TEXT NOT NULL DEFAULT '',
    pmid              TEXT NOT NULL DEFAULT '',
    title             TEXT NOT NULL DEFAULT '',
    title_fingerprint TEXT NOT NULL DEFAULT '',
    authors_json      TEXT NOT NULL DEFAULT '[]',
    year              INTEGER NOT NULL DEFAULT 0,
    -- Explicit, because "no year" and "year 0" must not be confused when a
    -- date filter is applied (acceptance case A04).
    year_known        INTEGER NOT NULL DEFAULT 0,
    venue             TEXT NOT NULL DEFAULT '',
    abstract          TEXT NOT NULL DEFAULT '',
    url               TEXT NOT NULL DEFAULT '',
    oa_pdf_url        TEXT NOT NULL DEFAULT '',
    source            TEXT NOT NULL DEFAULT '',    -- which platform produced it
    retrieved_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_literature_doi ON literature_items(doi) WHERE doi <> '';
CREATE INDEX idx_literature_arxiv ON literature_items(arxiv_id) WHERE arxiv_id <> '';
CREATE INDEX idx_literature_fingerprint
    ON literature_items(title_fingerprint) WHERE title_fingerprint <> '';

-- Candidate ↔ local file. Many-to-many on purpose: one work may have several
-- downloaded files (preprint and version of record).
CREATE TABLE literature_files (
    literature_id TEXT NOT NULL REFERENCES literature_items(literature_id),
    paper_id      TEXT NOT NULL REFERENCES papers(paper_id),
    origin        TEXT NOT NULL DEFAULT '',        -- upload | arxiv | oa_resolver | ...
    is_primary    INTEGER NOT NULL DEFAULT 1,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (literature_id, paper_id)
);
CREATE INDEX idx_literature_files_paper ON literature_files(paper_id);

CREATE TABLE session_papers (
    session_id    TEXT NOT NULL REFERENCES agent_sessions(session_id),
    literature_id TEXT NOT NULL REFERENCES literature_items(literature_id),
    paper_id      TEXT NOT NULL DEFAULT '',
    -- candidate: metadata only. pdf_ready: file stored. parsed: PaperIR built.
    -- unavailable: full text could not be obtained (acceptance case A08).
    availability  TEXT NOT NULL DEFAULT 'candidate',
    added_by      TEXT NOT NULL DEFAULT 'agent',   -- agent | user
    note          TEXT NOT NULL DEFAULT '',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (session_id, literature_id)
);
CREATE INDEX idx_session_papers_session ON session_papers(session_id, updated_at DESC);
CREATE INDEX idx_session_papers_paper ON session_papers(paper_id) WHERE paper_id <> '';

-- A parse of one PDF with one parser configuration. Evidence points at a
-- version, so re-parsing a paper cannot invalidate answers already given.
CREATE TABLE paper_versions (
    version_id    TEXT PRIMARY KEY,
    paper_id      TEXT NOT NULL REFERENCES papers(paper_id),
    parse_id      TEXT NOT NULL DEFAULT '',        -- mineru_parses.parse_id, when applicable
    parser        TEXT NOT NULL DEFAULT 'mineru',
    parser_config TEXT NOT NULL DEFAULT '{}',
    output_dir    TEXT NOT NULL DEFAULT '',
    -- Hash of the parsed content, so an identical re-parse reuses the version
    -- instead of creating a duplicate.
    content_hash  TEXT NOT NULL DEFAULT '',
    block_count   INTEGER NOT NULL DEFAULT 0,
    page_count    INTEGER NOT NULL DEFAULT 0,
    status        TEXT NOT NULL DEFAULT 'ready',   -- ready | superseded | failed
    is_current    INTEGER NOT NULL DEFAULT 1,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_paper_versions_paper ON paper_versions(paper_id, created_at DESC);
CREATE UNIQUE INDEX idx_paper_versions_current
    ON paper_versions(paper_id) WHERE is_current = 1;

-- Immutable. Rows are never updated: a changed quote is a different evidence
-- id, so a citation stored in an old answer always resolves to what was
-- actually read at the time.
CREATE TABLE evidence (
    evidence_id   TEXT PRIMARY KEY,
    owner_id      TEXT NOT NULL DEFAULT '',
    session_id    TEXT NOT NULL DEFAULT '',
    literature_id TEXT NOT NULL DEFAULT '',
    paper_id      TEXT NOT NULL DEFAULT '',        -- empty for metadata/web evidence
    parse_version TEXT NOT NULL DEFAULT '',        -- empty for non-PDF sources
    source_level  TEXT NOT NULL,                   -- fulltext|abstract|metadata|external_web
    -- Structured position: section path, 0-based page index, block range, bbox.
    -- Shape varies by source level, so it is JSON rather than columns.
    locator_json  TEXT NOT NULL DEFAULT '{}',
    quote         TEXT NOT NULL DEFAULT '',
    content_hash  TEXT NOT NULL DEFAULT '',
    source_url    TEXT NOT NULL DEFAULT '',
    provider      TEXT NOT NULL DEFAULT '',
    retrieved_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_evidence_session ON evidence(session_id, retrieved_at DESC);
CREATE INDEX idx_evidence_paper ON evidence(paper_id, parse_version);
CREATE INDEX idx_evidence_literature ON evidence(literature_id);
CREATE INDEX idx_evidence_owner ON evidence(owner_id) WHERE owner_id <> '';

-- ═══ Long-running jobs ═════════════════════════════════════════════════════
-- Downloads, parses and mode reports. The idempotency key is derived from the
-- work identity plus configuration, so a restart re-attaches to the job instead
-- of resubmitting it to the external service (acceptance case A13).
CREATE TABLE agent_jobs (
    job_id           TEXT PRIMARY KEY,
    kind             TEXT NOT NULL,                  -- download | parse | mode
    idempotency_key  TEXT NOT NULL,
    session_id       TEXT NOT NULL DEFAULT '',
    run_id           TEXT NOT NULL DEFAULT '',
    status           TEXT NOT NULL DEFAULT 'pending', -- pending|running|done|failed|cancelled
    attempts         INTEGER NOT NULL DEFAULT 0,
    -- Worker lease: a crashed worker's job is reclaimable once this passes.
    lease_owner      TEXT NOT NULL DEFAULT '',
    lease_expires_at TIMESTAMPTZ DEFAULT NULL,
    remote_id        TEXT NOT NULL DEFAULT '',       -- e.g. MinerU batch id, for recovery
    request_json     TEXT NOT NULL DEFAULT '{}',
    result_json      TEXT NOT NULL DEFAULT '{}',
    error_code       TEXT NOT NULL DEFAULT '',
    error_msg        TEXT NOT NULL DEFAULT '',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_agent_jobs_idempotent ON agent_jobs(idempotency_key);
CREATE INDEX idx_agent_jobs_claimable ON agent_jobs(status, lease_expires_at);
-- Jobs a crash left behind, found without scanning every job ever run.
CREATE INDEX idx_agent_jobs_running
    ON agent_jobs(status, lease_expires_at) WHERE status = 'running';

-- ═══ Long-term memory (P5) ═════════════════════════════════════════════════
-- Per principal, not per session: a preference stated in one conversation
-- should shape the next one, and the reader must be able to see and delete
-- what was kept.
CREATE TABLE agent_memories (
    memory_id         TEXT PRIMARY KEY,
    owner_id          TEXT NOT NULL,
    kind              TEXT NOT NULL DEFAULT 'preference',  -- preference | fact | project | instruction
    content           TEXT NOT NULL,
    source_session_id TEXT NOT NULL DEFAULT '',
    source_run_id     TEXT NOT NULL DEFAULT '',
    active            INTEGER NOT NULL DEFAULT 1,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_agent_memories_owner ON agent_memories(owner_id, active, updated_at DESC);
